const initialData = {
  tasks: {
    'task-1': { id: 'task-1', description: 'Tarefa 1 de teste' },
    'task-2': { id: 'task-2', description: 'Tarefa 2 de teste' },
    'task-3': { id: 'task-3', description: 'Tarefa 3 de teste' },
    'task-4': { id: 'task-4', description: 'Tarefa 4 de teste' },
    'task-5': { id: 'task-5', description: 'Tarefa 1 de teste' },
    'task-6': { id: 'task-6', description: 'Tarefa 2 de teste' },
    'task-7': { id: 'task-7', description: 'Tarefa 3 de teste' },
    'task-8': { id: 'task-8', description: 'Tarefa 4 de teste' },
    'task-9': { id: 'task-9', description: 'Tarefa 1 de teste' },
    'task-10': { id: 'task-10', description: 'Tarefa 2 de teste' },
    'task-11': { id: 'task-11', description: 'Tarefa 3 de teste' },
    'task-12': { id: 'task-12', description: 'Tarefa 4 de teste' },
  },
  columns: {
    'column-1': {
      id: 'column-1',
      color: '#ddd',
      colorLine: '#ccc',
      title: 'Para fazer',
      taskIds: [
        'task-1',
        'task-2',
        'task-3',
        'task-4',
        'task-5',
        'task-6',
        'task-7',
        'task-8',
        'task-9',
        'task-10',
        'task-11',
        'task-12',
      ],
    },
    'column-2': {
      id: 'column-2',
      color: '#ffff00aa',
      colorLine: '#ffff00',
      title: 'Em progresso',
      taskIds: [],
    },
    'column-3': {
      id: 'column-3',
      color: '#00ff5555',
      colorLine: '#04db00',
      title: 'Concluídas',
      taskIds: [],
    },
  },
  columnsOrder: ['column-1', 'column-2', 'column-3'],
};

export default initialData;
